# Site settings
title: "PySPOD: A parallel distributed SPOD package"
title-icon:
description: "PySPOD: A parallel distributed SPOD package"
keywords: "modal decomposition, dynamical system, computational physics"
featured-image:

# author settings for cc-by, appears in the footer and credits
author: mathe-lab
pub_year: 2022
github_username: mathe-lab
repo: "https://github.com/mathe-lab/PySPOD/"

# add search box to footer?
search: false

# add google analytics if desired (optional)
# if blank, it will be ignored
# use JEKYLL_ENV=production on build command
google_analytics:

# defaults (to simplify front matter)
defaults:
  - scope:
      path: "content"
    values:
      layout: "section"

# Build settings
theme: jekyll-theme-cayman

header_page_refs: ['now', 'about', 'contact']
