# Site settings
title: "PySPOD"
title-icon:
tagline: A parallel SPOD package
description: "A parallel SPOD package"
keywords: "modal decomposition, dynamical system, computational physics"
featured-image:
show_downloads: true

# author settings for cc-by, appears in the footer and credits
author: mathe-lab
pub_year: 2022
github_username: mathe-lab
repo: "https://github.com/mathe-lab/PySPOD/"

# add search box to footer?
search: false

# add google analytics if desired (optional)
# if blank, it will be ignored
# use JEKYLL_ENV=production on build command
google_analytics:

# defaults (to simplify front matter)
defaults:
  - scope:
      path: "content"
    values:
      layout: "section"

# Build settings
# theme: jekyll-theme-cayman
theme:

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['now', 'about', 'contact']
