name: ci

on:
  push:
    branches:
      - main
      - restructuring
  pull_request:
    branches:
      - main
      - restructuring
  workflow_dispatch:

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - macos-11
        mpi:
          - mpich
          - openmpi
        py:
          - "3.8"
          - "3.9"
          - "3.10"

    steps:

    - name: Configure hostname
      if:   runner.os == 'Linux' || runner.os == 'macOS'
      run:  echo 127.0.0.1 `hostname` | sudo tee -a /etc/hosts > /dev/null

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup MPI (${{ matrix.mpi }})
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: ${{ matrix.mpi }}

    - name: Use Python ${{ matrix.py }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.py }}
        architecture: x64

    - name: Install
      run: python -m pip install .[mpi,test]

    - name: Test mpiexec_pod
      run: mpiexec -np 2 python3 tests/test_pod_parallel.py

    - name: Test mpiexec_spod
      run: mpiexec -np 2 python3 tests/test_spod_parallel.py

    - name: Test mpiexec_utils
      run: mpiexec -np 2 python3 tests/test_utils_parallel.py

    - name: Test package
      run: coverage run --source ./pyspod -m pytest -v tests/

    - name: Coverage report
      run: coverage report
