name: release

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:

  sdist:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3

    - name: Upgrade pip
      run:  python -m pip install -U pip

    - name: Install build and twine
      run:  python -m pip install -U build twine

    - name: Build distribution
      run:  python -m build

    - name: Check source distribution
      run:  python -m twine check dist/pyspod-*.tar.gz

    - name: Check binary distribution
      run:  python -m twine check dist/pyspod-*.whl

    - name: Upload source distributionx
      uses: actions/upload-artifact@v3
      with:
        name: release
        path: |
          dist/*.tar.gz
          dist/*.whl
