name: website
on:
  push:
    branches:
      - main
      - restructuring
  pull_request:
    branches:
      - main
      - restructuring
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create site
        uses: actions/checkout@v2
        with:
          site-folder: "website/"

      # Deploy documentationa using packages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build/html
          allow_empty_commit: true
